nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x86
    - x64
    - arm64
    - ia32
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.4.1.cjs
